<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="67" started-at="2018-03-04T22:59:22Z" finished-at="2018-03-04T22:59:23Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="67" started-at="2018-03-04T22:59:22Z" finished-at="2018-03-04T22:59:23Z">
      <class name="com.qa.tests.DemoTest">
        <test-method status="PASS" signature="div()[pri:0, instance:com.qa.tests.DemoTest@7f9a81e8]" name="div" duration-ms="16" started-at="2018-03-04T16:59:23Z" finished-at="2018-03-04T16:59:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- div -->
        <test-method status="FAIL" signature="mul()[pri:0, instance:com.qa.tests.DemoTest@7f9a81e8]" name="mul" duration-ms="8" started-at="2018-03-04T16:59:23Z" finished-at="2018-03-04T16:59:23Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [2000]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [2000]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:388)
	at org.testng.Assert.assertEquals(Assert.java:398)
	at com.qa.tests.DemoTest.mul(DemoTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mul -->
        <test-method status="PASS" signature="sub()[pri:0, instance:com.qa.tests.DemoTest@7f9a81e8]" name="sub" duration-ms="5" started-at="2018-03-04T16:59:23Z" finished-at="2018-03-04T16:59:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sub -->
        <test-method status="PASS" signature="sum()[pri:0, instance:com.qa.tests.DemoTest@7f9a81e8]" name="sum" duration-ms="2" started-at="2018-03-04T16:59:23Z" finished-at="2018-03-04T16:59:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sum -->
      </class> <!-- com.qa.tests.DemoTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
